DROP TABLE IF EXISTS ACCOUNT;
CREATE TABLE ACCOUNT (
    USERNAME VARCHAR2(255) PRIMARY KEY,
    EMAIL VARCHAR2(255) UNIQUE,
    PASSWORD VARCHAR2(255),
    FIRSTNAME VARCHAR2(255),
    LASTNAME VARCHAR2(255)
);