DROP TABLE IF EXISTS ACCOUNT;
CREATE TABLE ACCOUNT (
   ID INT AUTO_INCREMENT PRIMARY KEY,
   USERNAME VARCHAR(255) UNIQUE NOT NULL,
   EMAIL VARCHAR(255) UNIQUE NOT NULL,
   ADMIN TINYINT(1) DEFAULT 0,
   PASSWORD VARCHAR(255) NOT NULL,
   FIRSTNAME VARCHAR(255),
   LASTNAME VARCHAR(255)
) ENGINE=InnoDB CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;